const KEY="ekima_full_system_v2";
let data=JSON.parse(localStorage.getItem(KEY)||"null")||{
sales:[],leads:[],service:[],parts:[],bluebook:[],outstanding:[],marketing:[],audit:[],training:[],po:[],warranty:[],purchases:[],inventory:[],transactions:[],accounts:[],journals:[],reminders:[],settings:{smsEnabled:false,emailEnabled:false,whatsappEnabled:true,aiEnabled:true},users:[
{id:1,name:"Administrator",username:"admin",role:"Admin",password:"1234"}
]};
let current=null, page="dashboard";
const modules={
dashboard:["🏠","Dashboard"],sales:["💰","Sales"],leads:["📞","Enquiry / Leads"],service:["🔧","Service"],parts:["📦","Parts Stock"],bluebook:["🚗","Bluebook Renewal"],outstanding:["💵","Outstanding"],marketing:["📣","Marketing"],audit:["🔍","Audit"],training:["🎓","Training"],po:["🛒","Purchase Order"],warranty:["🛡","Warranty"],purchases:["🧾","Purchases"],inventory:["📋","Inventory Transactions"],transactions:["💳","All Transactions"],accounting:["📊","Advanced Accounting"],reminders:["🔔","Reminders & Messages"],ai:["🤖","AI Control Center"],settings:["⚙️","System Settings"],users:["👥","Users / Staff"]
};
const schemas={
sales:{title:"Sales",fields:[["date","Date","date"],["person","Name of Costumer","text"],["mobil","Contact Number","number"], ["place","Adress","text"],["model","Model","text"],["booking","Booking","number"],["delivery","Delivery","number"],["amount","Sales Amount","number"],["discount","Discount","number"],["cogs","COGS","number"],["collection","Collection","number"],["payment","Payment Method (Cash/Bank/QR)","text"]]},
leads:{title:"Enquiry / Leads",fields:[["date","Date","date"],["customer","Customer","text"],["phone","Phone","text"],["source","Source","text"],["product","Product","text"],["person","Salesperson","text"],["stage","Stage","text"],["next","Next Follow-up","date"]]},
service:{title:"Service",fields:[["date","Date","date"],["job","Job Card","text"],["customer","Customer","text"],["phone","Phone","text"],["vehicle","Vehicle","text"],["service","Service Type","text"],["next","Next Service","date"],["status","Status","text"]]},
parts:{title:"Parts Stock",fields:[["partno","Part No","text"],["name","Part Name","text"],["opening","Opening","number"],["purchase","Purchase","number"],["issue","Issue/Sale","number"],["reorder","Reorder Level","number"]]},
bluebook:{title:"Bluebook Renewal",fields:[["customer","Customer","text"],["phone","Phone","text"],["vehicle","Vehicle No","text"],["expiry","Expiry Date","date"],["follow","Follow-up","text"]]},
outstanding:{title:"Outstanding",fields:[["customer","Customer","text"],["phone","Phone","text"],["invoice","Invoice","text"],["total","Total","number"],["paid","Paid","number"],["due","Due Date","date"],["follow","Follow-up","text"]]},
marketing:{title:"Marketing",fields:[["date","Date","date"],["activity","Activity","text"],["platform","Platform","text"],["cost","Cost","number"],["leads","Leads","number"],["bookings","Bookings","number"],["sales","Sales","number"]]},
audit:{title:"Audit",fields:[["date","Date","date"],["area","Area","text"],["point","Audit Point","text"],["finding","Finding","text"],["responsible","Responsible","text"],["deadline","Deadline","date"],["status","Status","text"]]},
training:{title:"Training",fields:[["date","Date","date"],["staff","Staff","text"],["topic","Topic","text"],["target","Target","text"],["completed","Completed","text"],["score","Score","number"]]},
po:{title:"Purchase Order",fields:[["pono","PO No","text"],["date","Date","date"],["supplier","Supplier","text"],["item","Item","text"],["qty","Qty","number"],["amount","Amount","number"],["expected","Expected Date","date"],["status","Status","text"]]},
warranty:{title:"Warranty",fields:[["claim","Claim No","text"],["date","Date","date"],["customer","Customer","text"],["phone","Phone","text"],["vehicle","Vehicle","text"],["part","Part","text"],["problem","Problem","text"],["claimstatus","Claim Status","text"],["companystatus","Company Status","text"]]}
,
purchases:{title:"Purchase Entry",fields:[["date","Date","date"],["supplier","Supplier","text"],["bill","Bill No","text"],["item","Item / Part","text"],["qty","Qty","number"],["rate","Rate","number"],["discount","Discount","number"],["vat","VAT %","number"],["payment","Payment Method","text"]]},
inventory:{title:"Inventory Transaction",fields:[["date","Date","date"],["item","Item / Part","text"],["type","Type (Purchase/Sale/Issue/Return)","text"],["ref","Reference","text"],["qty","Qty","number"],["rate","Rate","number"],["discount","Discount","number"],["payment","Payment Method","text"]]},
transactions:{title:"All Transaction",fields:[["date","Date","date"],["type","Transaction Type","text"],["ref","Reference","text"],["party","Customer/Supplier","text"],["debit","Debit","number"],["credit","Credit","number"],["discount","Discount","number"],["payment","Payment Method","text"],["note","Narration","text"]]},
accounts:{title:"Chart of Accounts",fields:[["code","Code","text"],["name","Account Name","text"],["type","Type (Asset/Liability/Equity/Income/Expense)","text"],["opening","Opening Balance","number"]]},
journals:{title:"Journal Entry",fields:[["date","Date","date"],["ref","Reference","text"],["account","Account","text"],["debit","Debit","number"],["credit","Credit","number"],["narration","Narration","text"]]}};
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function login(){let u=document.getElementById("user").value,p=document.getElementById("pass").value,r=document.getElementById("role").value;if(u==="admin"&&p==="1234"){current={name:"Administrator",role:r};document.getElementById("login").classList.add("hidden");document.getElementById("app").classList.remove("hidden");document.getElementById("who").textContent=current.name+" ("+current.role+")";buildNav();render()}else alert("Demo login: admin / 1234")}
function logout(){location.reload()}
function buildNav(){document.getElementById("nav").innerHTML=Object.entries(modules).map(([k,v])=>`<button class="navbtn ${page===k?"active":""}" onclick="go('${k}')">${v[0]} ${v[1]}</button>`).join("")}
function go(p){page=p;document.querySelector(".sidebar").classList.remove("open");buildNav();render()}
function money(n){return "Rs. "+Number(n||0).toLocaleString("en-IN")}
function today(){return new Date().toISOString().slice(0,10)}
function days(date){return date?Math.ceil((new Date(date)-new Date())/86400000):99999}
function status(s){s=(s||"").toLowerCase();return s.includes("pending")||s.includes("due")?"yellow":s.includes("expired")||s.includes("low")?"red":"green"}
function add(type,obj){obj.id=Date.now();data[type].push(obj);save();render()}
function form(type,record=null){
let s=schemas[type];
let editId=record?.id||"";
return `<div class="formgrid" id="form" data-edit-id="${editId}">${s.fields.map(([k,l,t])=>k==="payment"?`<select id="f_${k}" title="${l}"><option value="">Payment Method</option>${["Cash","Bank","QR"].map(v=>`<option ${record?.[k]===v?"selected":""}>${v}</option>`).join("")}</select>`:`<input id="f_${k}" type="${t}" placeholder="${l}" value="${esc(record?.[k]??"")}">`).join("")}</div>
<button class="btn" onclick="submitForm('${type}')">${editId?"Update Record":"Save Record"}</button>${editId?` <button class="btn secondary" onclick="render()">Cancel</button>`:""}`;} 
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function submitForm(type){
let obj={};schemas[type].fields.forEach(([k])=>obj[k]=document.getElementById("f_"+k)?.value||"");
let editId=Number(document.getElementById("form")?.dataset.editId||0);
if(editId){let i=data[type].findIndex(x=>x.id===editId);if(i>=0){obj.id=editId;data[type][i]=obj;save();render();return;}}
obj.id=Date.now();data[type].push(obj);postTransaction(type,obj);save();render()
}
function postTransaction(type,o){
let amount=0;
if(type==="sales"){amount=Math.max(0,(+o.amount||0)-(+o.discount||0)); data.transactions.push({id:Date.now()+1,date:o.date||today(),type:"Sales",ref:"SALE-"+o.id,party:o.person||"",debit:amount,credit:0,discount:+o.discount||0,payment:o.payment||"Cash",note:"Sales entry"});
addJournal(o.date||today(),"SALE-"+o.id,"Sales / Customer",amount,0,"Sales invoice");}
if(type==="purchases"){amount=Math.max(0,(+o.qty||0)*(+o.rate||0)-(+o.discount||0)); data.transactions.push({id:Date.now()+2,date:o.date||today(),type:"Purchase",ref:o.bill||("PUR-"+o.id),party:o.supplier||"",debit:0,credit:amount,discount:+o.discount||0,payment:o.payment||"Cash",note:"Purchase entry"});addJournal(o.date||today(),o.bill||("PUR-"+o.id),"Inventory / Supplier",amount,0,"Purchase entry");}
if(type==="inventory"){let total=Math.max(0,(+o.qty||0)*(+o.rate||0)-(+o.discount||0));data.transactions.push({id:Date.now()+3,date:o.date||today(),type:o.type||"Inventory",ref:o.ref||("INV-"+o.id),party:"",debit:total,credit:0,discount:+o.discount||0,payment:o.payment||"Cash",note:o.item||"Inventory transaction"});}
}
function addJournal(date,ref,account,debit,credit,narration){data.journals.push({id:Date.now()+Math.floor(Math.random()*1000),date,ref,account,debit,credit,narration});}
function editRecord(type,id){
let record=(data[type]||[]).find(x=>x.id===id);
if(!record)return;
let s=schemas[type];
document.getElementById("content").innerHTML=`<div class="wrap"><div class="head"><div><h1>Edit ${s.title}</h1><div class="page-note">Edit the saved record and click Update Record.</div></div></div><div class="panel">${form(type,record)}</div></div>`;
window.scrollTo({top:0,behavior:"smooth"});
}
function table(type){let s=schemas[type],rows=data[type]||[];let heads=s.fields.map(x=>x[1]);let out=`<div class="tablewrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join("")}<th>Action</th></tr></thead><tbody>`;rows.forEach(r=>{out+="<tr>";s.fields.forEach(([k])=>{let v=r[k]||"";if(type==="parts"&&k==="reorder"){out+=`<td>${v}</td>`}else out+=`<td>${v}</td>`});if(type==="bluebook"){let d=days(r.expiry);out+=`<td class="${status(d<0?"expired":d<=30?"pending":"normal")}">${d<0?"Expired":d+" days"}</td>`}else if(type==="parts"){let c=(+r.opening||0)+(+r.purchase||0)-(+r.issue||0);out+=`<td class="${status(c<=(+r.reorder||0)?"low":"normal")}">Closing ${c} ${c<=(+r.reorder||0)?"• LOW":""}</td>`}else if(type==="outstanding"){let o=(+r.total||0)-(+r.paid||0);out+=`<td>${money(o)} ${o>0?`<a class="btn mini wa" href="https://wa.me/${String(r.phone||"").replace(/\\D/g,"")}?text=${encodeURIComponent("Outstanding follow-up for "+(r.invoice||"invoice"))}" target="_blank">WhatsApp</a>`:"Paid"}</td>`}else out+=`<td>${r.status||r.claimstatus||r.companystatus||""}</td>`;out+=`<td><button class="btn mini" onclick="editRecord('${type}',${r.id})">Edit</button> <button class="btn mini danger" onclick="del('${type}',${r.id})">Delete</button></td></tr>`});return out+"</tbody></table></div>"}
function del(type,id){if(confirm("Delete record?")){data[type]=data[type].filter(x=>x.id!==id);save();render()}}
function render(){let c=document.getElementById("content");
if(page==="dashboard"){document.getElementById("title").textContent="Management Dashboard";c.innerHTML=dashboard();draw();return}
if(page==="users"){document.getElementById("title").textContent="Users / Staff";c.innerHTML=usersPage();return}
if(page==="accounting"){document.getElementById("title").textContent="Advanced Accounting";c.innerHTML=accountingPage();return}
if(page==="reminders"){document.getElementById("title").textContent="Reminders & Messages";c.innerHTML=remindersPage();return}
if(page==="ai"){document.getElementById("title").textContent="AI Control Center";c.innerHTML=aiPage();return}
if(page==="settings"){document.getElementById("title").textContent="System Settings";c.innerHTML=settingsPage();return}
let s=schemas[page];document.getElementById("title").textContent=s.title;
let tools=(page==="sales"||page==="purchases"||page==="inventory"||page==="transactions")?`<button class="btn" onclick="exportModule('${page}')">Export Excel</button> <button class="btn" onclick="printLatestVoucher('${page}')">Print Voucher PDF</button>`:"";
c.innerHTML=`<div class="wrap"><div class="head"><div><h1>${s.title}</h1><div class="page-note">Enter daily data. Dashboard and accounting update automatically.</div></div><div>${tools}</div></div><div class="panel">${form(page)}</div><div class="panel"><div class="toolbar"><input class="search" placeholder="Search records..." oninput="filterTable(this.value)"></div><div id="tbl">${table(page)}</div></div></div>`}


function accountingPage(){
let dr=data.journals.reduce((a,r)=>a+(+r.debit||0),0),cr=data.journals.reduce((a,r)=>a+(+r.credit||0),0);
let cash=data.transactions.filter(r=>String(r.payment).toLowerCase()==="cash").reduce((a,r)=>a+(+r.debit||0)-(+r.credit||0),0);
let bank=data.transactions.filter(r=>["bank","qr"].includes(String(r.payment).toLowerCase())).reduce((a,r)=>a+(+r.debit||0)-(+r.credit||0),0);
let income=data.sales.reduce((a,r)=>a+Math.max(0,(+r.amount||0)-(+r.discount||0)),0), cogs=data.sales.reduce((a,r)=>a+(+r.cogs||0),0), expense=data.purchases.reduce((a,r)=>a+Math.max(0,(+r.qty||0)*(+r.rate||0)-(+r.discount||0)),0);
return `<div class="wrap"><div class="head"><div><h1>Advanced Accounting Package</h1><div class="page-note">Double-entry-ready management accounting with Cash, Bank and QR tracking.</div></div><div><button class="btn" onclick="exportModule('transactions')">Excel Transactions</button> <button class="btn" onclick="printVoucher('ACCOUNTING','Accounting Summary')">PDF Summary</button></div></div>
<div class="cards"><div class="card"><label>Total Debit</label><strong>${money(dr)}</strong></div><div class="card"><label>Total Credit</label><strong>${money(cr)}</strong></div><div class="card"><label>Cash Balance</label><strong>${money(cash)}</strong></div><div class="card"><label>Bank + QR</label><strong>${money(bank)}</strong></div><div class="card"><label>Sales Income</label><strong>${money(income)}</strong></div><div class="card"><label>Purchase / Cost</label><strong>${money(expense)}</strong></div><div class="card"><label>Gross Profit</label><strong>${money(income-cogs)}</strong></div><div class="card"><label>Net Movement</label><strong>${money(dr-cr)}</strong></div></div>
<div class="grid"><div class="panel"><h3>Quick Accounting</h3><button class="btn" onclick="go('accounts')">Chart of Accounts</button> <button class="btn" onclick="go('journals')">Journal</button> <button class="btn" onclick="go('transactions')">Ledger / Transactions</button></div><div class="panel"><h3>Payment Controls</h3><p class="muted">Every sales/purchase/inventory entry supports Cash, Bank and QR. Discount is recorded separately.</p></div></div></div><div class="grid"><div class="panel"><h3>Trial Balance</h3><p>Debit: <b>${money(dr)}</b></p><p>Credit: <b>${money(cr)}</b></p><p>Difference: <b>${money(dr-cr)}</b></p></div><div class="panel"><h3>Profit & Loss</h3><p>Income: ${money(income)}</p><p>COGS: ${money(cogs)}</p><p>Purchase/Cost: ${money(expense)}</p><p><b>Estimated Operating Result: ${money(income-cogs-expense)}</b></p></div></div></div>`}
function remindersPage(){let rows=[];(data.outstanding||[]).forEach(r=>{let due=(+r.total||0)-(+r.paid||0);if(due>0)rows.push({type:"Outstanding",name:r.customer,phone:r.phone,text:"Dear "+(r.customer||"Customer")+", your outstanding amount is "+money(due)+". Please contact EKIMA Enterprises."})});(data.bluebook||[]).forEach(r=>{if(days(r.expiry)<=30)rows.push({type:"Bluebook",name:r.customer,phone:r.phone,text:"Dear "+(r.customer||"Customer")+", your Bluebook renewal is due on "+r.expiry+". Please contact EKIMA Enterprises."})});(data.leads||[]).filter(r=>r.next&&days(r.next)<=1).forEach(r=>rows.push({type:"Lead Follow-up",name:r.customer,phone:r.phone,text:"Namaste "+(r.customer||"Customer")+", this is a follow-up from EKIMA Enterprises regarding your enquiry."}));return `<div class="wrap"><div class="head"><div><h1>Reminders & Auto Messages</h1><div class="page-note">Prepare personalized SMS, Email and WhatsApp messages from your live records.</div></div><button class="btn" onclick="sendAllWhatsApp()">Open All WhatsApp</button></div><div class="panel"><table><thead><tr><th>Type</th><th>Customer</th><th>Message</th><th>Action</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${r.type}</td><td>${r.name||""}</td><td>${r.text}</td><td><a class="btn mini wa" target="_blank" href="https://wa.me/${String(r.phone||"").replace(/\D/g,"")}?text=${encodeURIComponent(r.text)}">WhatsApp</a> <button class="btn mini" onclick="copyMsg(${i})">Copy</button></td></tr>`).join("")||'<tr><td colspan="4">No reminders currently due.</td></tr>'}</tbody></table></div></div>`}
function sendAllWhatsApp(){let links=[...document.querySelectorAll('.wa')];links.forEach((a,i)=>setTimeout(()=>window.open(a.href,'_blank'),i*500))}
function aiPage(){let tips=[];let out=data.outstanding.reduce((a,r)=>a+Math.max(0,(+r.total||0)-(+r.paid||0)),0),low=data.parts.filter(r=>(+r.opening||0)+(+r.purchase||0)-(+r.issue||0)<=(+r.reorder||0)).length; if(out)tips.push("Prioritize outstanding collection: "+money(out));if(low)tips.push("Create purchase requests for "+low+" low-stock parts.");if(data.leads.length>data.sales.length*3)tips.push("Lead-to-sale conversion may need stronger follow-up.");if(!tips.length)tips.push("No critical rule-based alerts. Keep entering daily transactions for better control.");return `<div class="wrap"><div class="head"><div><h1>AI Control Center</h1><div class="page-note">AI-style decision support using your dashboard data. External AI/API can be connected later for true generative automation.</div></div></div><div class="panel"><h3>Recommended Actions</h3>${tips.map(x=>`<div class="alert yellow">🤖 ${x}</div>`).join("")}</div><div class="grid"><div class="panel"><h3>Automation Engine</h3><p>✓ Transaction monitoring<br>✓ Low-stock detection<br>✓ Outstanding reminders<br>✓ Bluebook/service follow-up<br>✓ Discount tracking<br>✓ Cash/Bank/QR classification</p></div><div class="panel"><h3>External AI & Messaging</h3><p class="muted">To make SMS, email, WhatsApp and AI fully automatic, connect approved provider APIs from System Settings. This browser package currently generates messages and opens WhatsApp safely without storing credentials.</p></div></div></div>`}
function settingsPage(){return `<div class="wrap"><div class="head"><div><h1>System Settings</h1><div class="page-note">Configure automation providers later without changing accounting data.</div></div></div><div class="panel"><h3>Automation</h3><label><input type="checkbox" ${data.settings.whatsappEnabled?'checked':''} onchange="toggleSetting('whatsappEnabled',this.checked)"> WhatsApp enabled</label><br><label><input type="checkbox" ${data.settings.smsEnabled?'checked':''} onchange="toggleSetting('smsEnabled',this.checked)"> SMS enabled</label><br><label><input type="checkbox" ${data.settings.emailEnabled?'checked':''} onchange="toggleSetting('emailEnabled',this.checked)"> Email enabled</label><br><label><input type="checkbox" ${data.settings.aiEnabled?'checked':''} onchange="toggleSetting('aiEnabled',this.checked)"> AI control enabled</label></div><div class="panel"><h3>Provider Integration</h3><p class="muted">API credentials are intentionally not embedded in this offline dashboard. For production, connect an SMS provider, email service, WhatsApp Business provider and secure AI API through a backend.</p></div></div>`}
function toggleSetting(k,v){data.settings[k]=v;save()}
function exportModule(type){let rows=data[type]||[];if(!window.XLSX){alert('Excel library not loaded.');return}let ws=XLSX.utils.json_to_sheet(rows.length?rows:[{}]);let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,schemas[type]?.title||type);XLSX.writeFile(wb,'EKIMA_'+type+'_export.xlsx')}
function printLatestVoucher(type){let rows=data[type]||[];if(!rows.length){alert('No record available.');return}printVoucher(type,JSON.stringify(rows[rows.length-1],null,2))}
function printVoucher(title,body){if(!window.jspdf){alert('PDF library not loaded.');return}let {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(18);doc.text('EKIMA ENTERPRISES PVT. LTD.',20,20);doc.setFontSize(14);doc.text(String(title)+' VOUCHER',20,32);doc.setFontSize(10);let lines=String(body).split('\n');let y=45;lines.forEach(line=>{doc.text(line.slice(0,110),20,y);y+=6;if(y>280){doc.addPage();y=20}});doc.text('Generated: '+new Date().toLocaleString(),20,290);doc.save('EKIMA_'+String(title).replace(/\W+/g,'_')+'_voucher.pdf')}
function copyMsg(i){let wa=[...document.querySelectorAll('.wa')][i];if(wa)navigator.clipboard?.writeText(decodeURIComponent((wa.href.split('text=')[1]||'').replace(/\+/g,' '))).then(()=>alert('Message copied.'))}
function dashboard(){let sales=data.sales.reduce((a,r)=>a+(+r.amount||0),0),cogs=data.sales.reduce((a,r)=>a+(+r.cogs||0),0),col=data.sales.reduce((a,r)=>a+(+r.collection||0),0),out=data.outstanding.reduce((a,r)=>a+Math.max(0,(+r.total||0)-(+r.paid||0)),0),blue=data.bluebook.filter(r=>days(r.expiry)<=30).length,low=data.parts.filter(r=>(+r.opening||0)+(+r.purchase||0)-(+r.issue||0)<=(+r.reorder||0)).length,pendingService=data.service.filter(r=>(r.status||"").toLowerCase()!=="complete").length,audit=data.audit.filter(r=>(r.status||"pending").toLowerCase()==="pending").length,po=data.po.filter(r=>(r.status||"pending").toLowerCase()==="pending").length,warranty=data.warranty.filter(r=>(r.claimstatus||"pending").toLowerCase()==="pending"||(r.companystatus||"pending").toLowerCase()==="pending").length;
return `<div class="wrap"><div class="head"><div><h1>Business Management Dashboard</h1><div class="muted">Real-time browser dashboard • ${today()}</div></div><button class="btn" onclick="exportData()">Export Backup</button></div>
<div class="cards">${[
["Sales",money(sales)], ["Purchases",money(data.purchases.reduce((a,r)=>a+Math.max(0,(+r.qty||0)*(+r.rate||0)-(+r.discount||0)),0))],["Gross Profit",money(sales-cogs)],["Collection",money(col)],["Outstanding",money(out)],["Leads",data.leads.length],["Booking",data.sales.reduce((a,r)=>a+(+r.booking||0),0)],["Delivery",data.sales.reduce((a,r)=>a+(+r.delivery||0),0)],["Service Jobs",data.service.length],["Bluebook Due",blue],["Low Stock",low],["Audit Pending",audit],["Warranty Pending",warranty]].map(x=>`<div class="card"><label>${x[0]}</label><strong>${x[1]}</strong></div>`).join("")}</div>
<div class="grid"><div class="panel"><h3>Sales Trend</h3><canvas id="chart"></canvas></div><div class="panel"><h3>Management Alerts</h3>
${out?`<div class="alert red">🔴 Outstanding ${money(out)} — collection follow-up</div>`:""}${blue?`<div class="alert yellow">🟡 ${blue} Bluebook renewal(s) due within 30 days</div>`:""}${low?`<div class="alert red">🔴 ${low} parts below reorder level</div>`:""}${pendingService?`<div class="alert yellow">🟡 ${pendingService} service job(s) not complete</div>`:""}${audit?`<div class="alert yellow">🟡 ${audit} audit finding(s) pending</div>`:""}${po?`<div class="alert yellow">🟡 ${po} PO(s) pending</div>`:""}${warranty?`<div class="alert yellow">🟡 ${warranty} warranty item(s) pending</div>`:""}${!out&&!blue&&!low&&!pendingService&&!audit&&!po&&!warranty?'<div class="alert green">🟢 No major alerts</div>':''}</div></div>
<div class="panel"><h3>Manager Rule</h3><p class="kpi"><b>DATA → KPI → DASHBOARD → ALERT → ACTION → REVIEW</b></p><p class="muted">Manager should start from red alerts, assign a responsible person, set a deadline and review the result.</p></div></div>`}
function usersPage(){return `<div class="wrap"><div class="head"><h1>Users / Staff</h1></div><div class="panel"><p class="page-note">Demo role control is included. Production deployment should use a secure server/database and hashed passwords.</p>${data.users.map(u=>`<p><b>${u.name}</b> — ${u.role} — ${u.username}</p>`).join("")}</div></div>`}
function filterTable(q){let t=document.querySelector("#tbl tbody");if(!t)return;[...t.rows].forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q.toLowerCase())?"":"none")}
function draw(){setTimeout(()=>{let ctx=document.getElementById("chart");if(!ctx)return;let rows=data.sales.slice(-10);new Chart(ctx,{type:"bar",data:{labels:rows.map(r=>r.date||"Sale"),datasets:[{label:"Sales Amount",data:rows.map(r=>+r.amount||0),borderWidth:1}]},options:{responsive:true,scales:{y:{beginAtZero:true}}}})},20)}
function exportData(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="ekima-backup.json";a.click()}
setInterval(()=>document.getElementById("clock").textContent=new Date().toLocaleString(),1000);
